export enum TempleMessageType {
    // Aknowledge
    Acknowledge = 'TEMPLE_CONNECT_AKNOWLEDGE',
    // Notifications
    StateUpdated = 'TEMPLE_STATE_UPDATED',
    ConfirmationRequested = 'TEMPLE_CONFIRMATION_REQUESTED',
    ConfirmationExpired = 'TEMPLE_CONFIRMATION_EXPIRED',
    SelectedAccountChanged = 'TEMPLE_SELECTED_ACCOUNT_CHANGED',
    // Request-Response pairs
    GetStateRequest = 'TEMPLE_GET_STATE_REQUEST',
    GetStateResponse = 'TEMPLE_GET_STATE_RESPONSE',
    NewWalletRequest = 'TEMPLE_NEW_WALLET_REQUEST',
    NewWalletResponse = 'TEMPLE_NEW_WALLET_RESPONSE',
    UnlockRequest = 'TEMPLE_UNLOCK_REQUEST',
    UnlockResponse = 'TEMPLE_UNLOCK_RESPONSE',
    LockRequest = 'TEMPLE_LOCK_REQUEST',
    LockResponse = 'TEMPLE_LOCK_RESPONSE',
    CreateAccountRequest = 'TEMPLE_CREATE_ACCOUNT_REQUEST',
    CreateAccountResponse = 'TEMPLE_CREATE_ACCOUNT_RESPONSE',
    RevealPublicKeyRequest = 'TEMPLE_REVEAL_PUBLIC_KEY_REQUEST',
    RevealPublicKeyResponse = 'TEMPLE_REVEAL_PUBLIC_KEY_RESPONSE',
    RevealPrivateKeyRequest = 'TEMPLE_REVEAL_PRIVATE_KEY_REQUEST',
    RevealPrivateKeyResponse = 'TEMPLE_REVEAL_PRIVATE_KEY_RESPONSE',
    RevealMnemonicRequest = 'TEMPLE_REVEAL_MNEMONIC_REQUEST',
    RevealMnemonicResponse = 'TEMPLE_REVEAL_MNEMONIC_RESPONSE',
    GenerateSyncPayloadRequest = 'TEMPLE_GENERATE_SYNC_PAYLOAD_REQUEST',
    GenerateSyncPayloadResponse = 'TEMPLE_GENERATE_SYNC_PAYLOAD_RESPONSE',
    RemoveAccountRequest = 'TEMPLE_REMOVE_ACCOUNT_REQUEST',
    RemoveAccountResponse = 'TEMPLE_REMOVE_ACCOUNT_RESPONSE',
    EditAccountRequest = 'TEMPLE_EDIT_ACCOUNT_REQUEST',
    EditAccountResponse = 'TEMPLE_EDIT_ACCOUNT_RESPONSE',
    ImportAccountRequest = 'TEMPLE_IMPORT_ACCOUNT_REQUEST',
    ImportAccountResponse = 'TEMPLE_IMPORT_ACCOUNT_RESPONSE',
    ImportMnemonicAccountRequest = 'TEMPLE_IMPORT_MNEMONIC_ACCOUNT_REQUEST',
    ImportMnemonicAccountResponse = 'TEMPLE_IMPORT_MNEMONIC_ACCOUNT_RESPONSE',
    ImportFundraiserAccountRequest = 'TEMPLE_IMPORT_FUNDRAISER_ACCOUNT_REQUEST',
    ImportFundraiserAccountResponse = 'TEMPLE_IMPORT_FUNDRAISER_ACCOUNT_RESPONSE',
    ImportManagedKTAccountRequest = 'TEMPLE_IMPORT_MANAGED_KT_ACCOUNT_REQUEST',
    ImportManagedKTAccountResponse = 'TEMPLE_IMPORT_MANAGED_KT_ACCOUNT_RESPONSE',
    ImportWatchOnlyAccountRequest = 'TEMPLE_IMPORT_WATCH_ONLY_ACCOUNT_REQUEST',
    ImportWatchOnlyAccountResponse = 'TEMPLE_IMPORT_WATCH_ONLY_ACCOUNT_RESPONSE',
    CreateLedgerAccountRequest = 'TEMPLE_CREATE_LEDGER_ACCOUNT_REQUEST',
    CreateLedgerAccountResponse = 'TEMPLE_CREATE_LEDGER_ACCOUNT_RESPONSE',
    UpdateSettingsRequest = 'TEMPLE_UPDATE_SETTINGS_REQUEST',
    UpdateSettingsResponse = 'TEMPLE_UPDATE_SETTINGS_RESPONSE',
    OperationsRequest = 'TEMPLE_OPERATIONS_REQUEST',
    OperationsResponse = 'TEMPLE_OPERATIONS_RESPONSE',
    SignRequest = 'TEMPLE_SIGN_REQUEST',
    SignResponse = 'TEMPLE_SIGN_RESPONSE',
    ConfirmationRequest = 'TEMPLE_CONFIRMATION_REQUEST',
    ConfirmationResponse = 'TEMPLE_CONFIRMATION_RESPONSE',
    PageRequest = 'TEMPLE_PAGE_REQUEST',
    PageResponse = 'TEMPLE_PAGE_RESPONSE',
    DAppGetPayloadRequest = 'TEMPLE_DAPP_GET_PAYLOAD_REQUEST',
    DAppGetPayloadResponse = 'TEMPLE_DAPP_GET_PAYLOAD_RESPONSE',
    DAppPermConfirmationRequest = 'TEMPLE_DAPP_PERM_CONFIRMATION_REQUEST',
    DAppPermConfirmationResponse = 'TEMPLE_DAPP_PERM_CONFIRMATION_RESPONSE',
    DAppOpsConfirmationRequest = 'TEMPLE_DAPP_OPS_CONFIRMATION_REQUEST',
    DAppOpsConfirmationResponse = 'TEMPLE_DAPP_OPS_CONFIRMATION_RESPONSE',
    DAppSignConfirmationRequest = 'TEMPLE_DAPP_SIGN_CONFIRMATION_REQUEST',
    DAppSignConfirmationResponse = 'TEMPLE_DAPP_SIGN_CONFIRMATION_RESPONSE',
    DAppGetAllSessionsRequest = 'TEMPLE_DAPP_GET_ALL_SESSIONS_REQUEST',
    DAppGetAllSessionsResponse = 'TEMPLE_DAPP_GET_ALL_SESSIONS_RESPONSE',
    DAppRemoveSessionRequest = 'TEMPLE_DAPP_REMOVE_SESSION_REQUEST',
    DAppRemoveSessionResponse = 'TEMPLE_DAPP_REMOVE_SESSION_RESPONSE',
    SendTrackEventRequest = 'SEND_TRACK_EVENT_REQUEST',
    SendTrackEventResponse = 'SEND_TRACK_EVENT_RESPONSE',
    SendPageEventRequest = 'SEND_PAGE_EVENT_REQUEST',
    SendPageEventResponse = 'SEND_PAGE_EVENT_RESPONSE'
}

export enum MessageType {
    Acknowledge = 'acknowledge',

    PermissionRequest = 'permission_request',
    SignPayloadRequest = 'sign_payload_request',
    OperationRequest = 'operation_request',
    BroadcastRequest = 'broadcast_request',
    PermissionResponse = 'permission_response',
    SignPayloadResponse = 'sign_payload_response',
    OperationResponse = 'operation_response',
    BroadcastResponse = 'broadcast_response',
    Disconnect = 'disconnect',
    Error = 'error',
    // Handshake
    HandshakeRequest = 'postmessage-pairing-request',
    HandshakeResponse = 'postmessage-pairing-response'
}

export enum TempleDAppMessageType {
    GetCurrentPermissionRequest = "GET_CURRENT_PERMISSION_REQUEST",
    GetCurrentPermissionResponse = "GET_CURRENT_PERMISSION_RESPONSE",
    PermissionRequest = "PERMISSION_REQUEST",
    PermissionResponse = "PERMISSION_RESPONSE",
    OperationRequest = "OPERATION_REQUEST",
    OperationResponse = "OPERATION_RESPONSE",
    SignRequest = "SIGN_REQUEST",
    SignResponse = "SIGN_RESPONSE",
    BroadcastRequest = "BROADCAST_REQUEST",
    BroadcastResponse = "BROADCAST_RESPONSE",
}